apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weather-app
  namespace: flux-system  # Flux applies the manifests from this namespace
spec:
  interval: 1m
  path: ./k8s-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: weather-app  # Namespace where resources are deployed
